Mikolajb/dev/#12 Added flow for publisher
DontEatRice/BookBook pull request #20
Opened 2023-06-04 16:38 UTC by bmikolajj

2023-06-04 17:19 UTC, jgulinski requested changes
Dobra robota

2023-06-04 17:19 UTC, jgulinski commented on Server/src/Server.Application/Command/Handlers/RemovePublisherHandler.cs
> +public class RemovePublisherHandler
Ta klasa powinna dziedziczyć bo `ICommandHandler` i w metodzie `HandleAsync` nic nie zwracać

2023-06-04 17:19 UTC, jgulinski commented on Server/src/Server.Domain/Entities/Publisher.cs
>      [Required, MaxLength(50)]
te adnotacje powinny być usunięte, chcemy korzystać tylko z PublisherConfiguration

2023-06-09 18:25 UTC, DontEatRice commented on .vs/BookBook/v17/.suo
proszę usunąć

2023-06-09 18:26 UTC, DontEatRice commented on .vs/slnx.sqlite
skąd to się bierze wgl xd

2023-06-11 17:13 UTC, DontEatRice approved these changes

2023-06-11 17:16 UTC, jgulinski approved these changes

2023-06-11 17:16 UTC, merged