Improve the ui
DontEatRice/BookBook pull request #86
Opened 2023-10-28 12:00 UTC by jgulinski

2023-10-28 12:39 UTC, michaljn2 requested changes

2023-10-28 12:39 UTC, michaljn2 commented on .vs/BookBook/v17/.suo
Chyba do wywalenia

2023-10-28 12:39 UTC, michaljn2 commented on client/src/components/reservations/Cart.tsx
> +                  <ListItem
Chyba warto dodawać key do każdego elementu listy/grida

2023-10-28 14:33 UTC, jgulinski commented on .vs/BookBook/v17/.suo
tak, zostało ze zmian Mikołaja

2023-10-29 20:14 UTC, michaljn2 approved these changes

2023-10-29 20:14 UTC, merged